import type { Inquiry } from './types'

export const INITIAL_INQUIRIES: Inquiry[] = [
  {
    id: 'inq-01',
    productId: 'prod-01',
    productName: '순창 재래식 된장',
    author: '김지훈',
    isSecret: false,
    content: '된장 유통기한이 얼마나 되나요?',
    answerContent: '구매일로부터 1년입니다. 서늘한 곳에 보관해 주세요.',
    createdAt: '2026-08-02',
    answeredAt: '2026-08-03',
  },
  {
    id: 'inq-02',
    productId: 'prod-01',
    productName: '순창 재래식 된장',
    author: '오세훈',
    isSecret: true,
    content: '배송 중 파손된 것 같은데 환불 가능한가요?',
    answerContent: null,
    createdAt: '2026-08-15',
    answeredAt: null,
  },
  {
    id: 'inq-03',
    productId: 'prod-03',
    productName: '유기농 현미',
    author: '한지민',
    isSecret: false,
    content: '현미 도정일자를 알 수 있을까요?',
    answerContent: '매주 화/금요일에 도정하여 발송합니다.',
    createdAt: '2026-09-02',
    answeredAt: '2026-09-02',
  },
  {
    id: 'inq-04',
    productId: 'prod-04',
    productName: '제주 감귤칩',
    author: '윤아름',
    isSecret: false,
    content: '알레르기 유발 성분이 포함되어 있나요?',
    answerContent: null,
    createdAt: '2026-09-10',
    answeredAt: null,
  },
  {
    id: 'inq-05',
    productId: 'prod-02',
    productName: '남해 멸치액젓',
    author: '조현우',
    isSecret: true,
    content: '대량 구매 시 추가 할인이 가능한가요?',
    answerContent: null,
    createdAt: '2026-09-12',
    answeredAt: null,
  },
]
