name: Frontend Docker CI
on:
  push: 
      branches:
        - main

jobs: 
  docker:
    runs-on: ubuntu-latest
    steps:
    # 1. GitHub 저장소의 코드를 가져옴
      - name: checkout
        uses: actions/checkout@v4 
    # 2. Docker Hub 로그인
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 3. Docker 이미지 빌드 + Docker Hub push
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: ./client
          push: true
          tags: gimaw/my-react-app:latest
  deploy:
      # docker job이 성공해야만 이 job이 시작됩니다
      needs: docker
      runs-on: ubuntu-latest
      steps: 
          - name: SSH로 EC2에 접속해서 배포
            uses: appleboy/ssh-action@v1
            with:
              host: ${{ secrets.EC2_HOST }}
              username: ${{secrets.EC2_USERNAME}}
              key: ${{secrets.EC2_SSH_KEY}}
              script : |
                sudo docker pull gimaw/my-react-app:latest
                sudo docker stop my-react-app
                sudo docker rm my-react-app
                sudo docker run -d --name my-react-app -p 80:80 gimaw/my-react-app:latest
